name: Deploy to Amazon EC2

on:
  push:
    branches:
      - master
env:
  AWS_REGION: ap-northeast-2
  CODE_DEPLOY_APPLICATION_NAME: metapop-codedeploy-app
  CODE_DEPLOY_DEPLOYMENT_GROUP_NAME: metapop-codedeploy-group
  
jobs:
  deploy:
    name: deploy
    runs-on: ubuntu-latest
    steps:
      # Step 1
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}

      # Step 2
      - name: Create CodeDeploy Deployment
        id: deploy
        run: |
          aws deploy create-deployment \
            --application-name ${{ env.CODE_DEPLOY_APPLICATION_NAME }} \
            --deployment-group-name ${{ env.CODE_DEPLOY_GROUP_NAME }} \
            --deployment-config-name CodeDeployDefault.OneAtATime \
            --github-location repository=${{ github.repository }},commitId=${{ github.sha }}
